# IOT_BLE_SERVER_VERSION = 1.0
IOT_BLE_SERVER_SITE = https://github.com/qkb2/bluez-gatt.git
IOT_BLE_SERVER_SITE_METHOD = git

IOT_BLE_SERVER_DEPENDENCIES = libpthread
IOT_BLE_SERVER_CONF_OPTS += \
        -DBLE_MAC=\"$(BR2_PACKAGE_IOT_BLE_SERVER_MAC)\"


ifeq ($(BR2_PACKAGE_IOT_BLE_SERVER_VERBOSE),y)
IOT_BLE_SERVER_CONF_OPTS += -DVERBOSE=ON
endif

$(eval $(cmake-package))