IOT_BLE_SERVER_VERSION = cfd5f691061ea6aa59690d0f5073a8b5c609ff7b
IOT_BLE_SERVER_SITE = https://github.com/qkb2/bluez-gatt.git
IOT_BLE_SERVER_SITE_METHOD = git

IOT_BLE_SERVER_CONF_OPTS += \
        -DBLE_MAC=$(BR2_PACKAGE_IOT_BLE_SERVER_MAC)


ifeq ($(BR2_PACKAGE_IOT_BLE_SERVER_VERBOSE),y)
IOT_BLE_SERVER_CONF_OPTS += -DVERBOSE=ON
endif

$(eval $(cmake-package))
