IOT_BLE_SERVER_VERSION = 429247668ee8be1962cdebb33278f1a21434c592
IOT_BLE_SERVER_SITE = https://github.com/qkb2/bluez-gatt.git
IOT_BLE_SERVER_SITE_METHOD = git

IOT_BLE_SERVER_CONF_OPTS += \
        -DBLE_MAC=$(BR2_PACKAGE_IOT_BLE_SERVER_MAC)


ifeq ($(BR2_PACKAGE_IOT_BLE_SERVER_VERBOSE),y)
IOT_BLE_SERVER_CONF_OPTS += -DVERBOSE=ON
endif

IOT_BLE_SERVER_CONF_OPTS += \
	-DBUILD_SHARED_LIBS=OFF \
	-DCMAKE_EXE_LINKER_FLAGS="$(TARGET_LDFLAGS) -static"

$(eval $(cmake-package))

define IOT_BLE_SERVER_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 \
		$(IOT_BLE_SERVER_PKGDIR)/S99iot_ble_server \
		$(TARGET_DIR)/etc/init.d/S99iot_ble_server
endef
